Decorator v3
navikt/rekrutteringsbistand pull request #242
Opened 2024-10-01 20:30 UTC by Wiklem

2024-10-02 05:22 UTC, vildestefferud requested changes
Vi trenger å legge til prod-url, eller ser det bra ut

2024-10-02 05:22 UTC, vildestefferud commented on src/felles/header/modiadekoratør/Modiadekoratør.tsx
> +    const proxyUrl = 'https://rekrutteringsbistand.intern.dev.nav.no'; // todo legg til prod-url
Når skal vi legge til prod-url?

2024-10-02 06:58 UTC, Wiklem commented on src/felles/header/modiadekoratør/Modiadekoratør.tsx
> +    const proxyUrl = 'https://rekrutteringsbistand.intern.dev.nav.no'; // todo legg til prod-url
Er bare å gjøre med en gang ^^

Henta bare ikke tak i den i går, men kan gjøre det nå.

2024-10-02 07:02 UTC, Wiklem commented on src/felles/header/modiadekoratør/Modiadekoratør.tsx
> +    const proxyUrl = 'https://rekrutteringsbistand.intern.dev.nav.no'; // todo legg til prod-url
Regner med den kan hentes ut fra env, men hardkodet den bare inn avhenging av getMiljø()

2024-10-03 07:31 UTC, vildestefferud approved these changes

2024-10-03 10:24 UTC, joarau approved these changes

2024-10-03 12:58 UTC, merged